const KEY='bigp-log-data-v1';
let db=JSON.parse(localStorage.getItem(KEY)||'{}'); let view='today', selected=today(), month=new Date(); let open=null;
const opts={
 sleepQuality:['好','一般','差'],dream:['多梦','无梦','忘了'],exercise:['步行','跑步','骑行','游泳','瑜伽','普拉提','力量训练','核心训练','高强度间歇训练','八段锦','太极','跳绳','舞蹈','登山','羽毛球','其他'],feel:['更有精神','一般','疲惫'],
 stool:['成型香蕉便','成型黏糊便','排不尽黏糊便','软块不成条便','黏糊蹿稀','拉水'],fart:['响屁无味','响屁臭屁','不响臭屁'],emotion:['开心','激动','平静','一般','沮丧','愤怒','伤感','焦虑'],social:['文字信息','语音电话','视频','线下面对面'],periodSymptoms:['痛经（轻）','痛经（中）','痛经（重）','头晕','腹泻','失眠','多汗','经前乳房胀痛','血块','阴部瘙痒'],
 supplements:['Doctor’s Best PepZinGI','Thorne Berberine','Biocidin Remove','NOW NAC 600mg','NOW B-50','NOW Glycine 1000mg','NOW Odorless Garlic','NOW L-Glutamine 500mg']
};
const foodGroups={主食:['米饭','面条','馒头','面包','燕麦','玉米','红薯'],蛋白质:['鸡蛋','鸡肉','牛肉','猪肉','鱼','虾','豆腐','豆类'],蔬菜:['绿叶菜','西兰花','番茄','黄瓜','菌菇','根茎类'],水果:['苹果','香蕉','蓝莓','橙子','葡萄','其他水果'],奶制品:['牛奶','酸奶','奶酪'],零食:['坚果','饼干','糖果','薯片'],饮料:['咖啡','茶','果汁','含糖饮料']};
function today(){return new Date().toISOString().slice(0,10)} function save(){localStorage.setItem(KEY,JSON.stringify(db))} function log(){return db[selected]||(db[selected]={})}
function roman(n){const m=[[1000,'M'],[900,'CM'],[500,'D'],[400,'CD'],[100,'C'],[90,'XC'],[50,'L'],[40,'XL'],[10,'X'],[9,'IX'],[5,'V'],[4,'IV'],[1,'I']];return m.map(([v,s])=>{let r='';while(n>=v){r+=s;n-=v}return r}).join('')}
function lunarDay(n){const a=['初一','初二','初三','初四','初五','初六','初七','初八','初九','初十','十一','十二','十三','十四','十五','十六','十七','十八','十九','二十','廿一','廿二','廿三','廿四','廿五','廿六','廿七','廿八','廿九','三十'];return a[n-1]||''}
function lunar(d){try{let s=new Intl.DateTimeFormat('zh-CN-u-ca-chinese',{month:'long',day:'numeric'}).format(new Date(d+'T12:00:00'));let n=Number(s.match(/\d+/)?.[0]);return s.replace(/\d+日?/,lunarDay(n))}catch{return '农历'}}
function solar(d){return new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'long',day:'numeric'}).format(d)}
function phase(date){let starts=Object.entries(db).filter(([,v])=>v.body?.period==='是'&&v.body?.periodDay==='1').map(([d])=>d).sort();let last=starts.filter(d=>d<=date).pop();if(!last)return '等待记录经期';let diff=Math.floor((new Date(date)-new Date(last))/864e5)+1,day=((diff-1)%38)+1;return day<=7?'经期':day<=13?'卵泡期':day<=16?'排卵期':'黄体期'}
function choice(field,items,multi=false,value=''){return `<div class="options">${items.map(x=>`<button class="option ${multi?(value||[]).includes(x)?'selected':'':value===x?'selected':''}" data-choice="${field}" data-value="${x}" data-multi="${multi}">${x}</button>`).join('')}</div>`}
function input(field,label,type='text',value=''){return `<div class="field"><label class="label">${label}</label><input class="input" data-field="${field}" type="${type}" value="${value||''}"></div>`}
function text(field,label,value=''){return `<div class="field"><label class="label">${label}</label><textarea data-field="${field}" placeholder="写一点今天的内容…">${value||''}</textarea></div>`}
function section(id,title,content,color){return `<article class="section"><button class="section-head" data-toggle="${id}"><i class="dot" style="background:${color}"></i><span class="section-title">${title}</span><span class="chev">${open===id?'⌃':'⌄'}</span></button><div class="form ${open===id?'':'hidden'}">${content}</div></article>`}
function duration(start,end){if(!start||!end)return '';let [a,b]=start.split(':').map(Number),[c,d]=end.split(':').map(Number),mins=c*60+d-a*60-b;if(mins<=0)mins+=1440;let h=Math.floor(mins/60),m=mins%60;return `${h?`${h} 小时`:''}${m?`${m} 分钟`:''}`}
function timePair(prefix,v={}){let label=prefix==='sleep'?'睡眠时长':'运动时长',total=duration(v.start,v.end);return `<div class="row">${input(prefix+'Start','开始时间','time',v.start)}${input(prefix+'End','结束时间','time',v.end)}</div><div class="notice">${label}：${total||'选择时间后自动计算'}</div>`}
function entries(kind,title,render){let arr=log()[kind]||[];return `<div class="entry-list">${arr.map((x,i)=>`<div class="entry" data-entry="${kind}" data-index="${i}">${render(x,i)}${i||arr.length>1?`<button class="remove" data-remove="${kind}" data-index="${i}">删除</button>`:''}</div>`).join('')}</div><button class="add" data-add="${kind}">＋ ${title}</button>`}
function formSleep(v){return timePair('sleep',v)+`<div class="field"><label class="label">睡眠质量</label>${choice('sleep.quality',opts.sleepQuality,false,v.quality)}</div><div class="field"><label class="label">做梦情况</label>${choice('sleep.dream',opts.dream,false,v.dream)}</div>`}
function todayPage(){let v=log();let d=new Date(selected+'T12:00:00');let head=`<header class="top"><div><div class="date">${solar(d)}</div><div class="subdate">农历${lunar(selected)}</div><div class="cycle">${phase(selected)}</div></div><div class="nav"><button data-view="calendar" aria-label="月历">‹</button><button data-view="settings" aria-label="设置">···</button></div></header>`;
let content=''; content+=section('sleep','睡眠',formSleep(v.sleep||{}),'#7799ad');
content+=section('exercise','运动',`${choice('exercise.type',opts.exercise,false,v.exercise?.type)}${timePair('exercise',v.exercise||{})}<div class="field"><label class="label">运动后的感受</label>${choice('exercise.feel',opts.feel,false,v.exercise?.feel)}</div>`,'#db8c70');
content+=section('food','饮食',entries('meals','添加一餐',(x,i)=>`${input('time','用餐时间','time',x.time)}<div class="field"><label class="label">食材（可多选）</label>${Object.entries(foodGroups).map(([g,a])=>`<div class="label">${g}</div>${choice('foods',a,true,x.foods||[])}`).join('')}</div>${choice('snack',['吃了零食','没有吃零食'],false,x.snack||'')}`),'#d7af4e');
content+=section('stool','排便情况',entries('stools','添加一次排便',(x)=>`${input('time','排便时间','time',x.time)}<div class="field"><label class="label">排便状态</label>${choice('state',opts.stool,false,x.state)}</div>`),'#b48d63');
content+=section('body','身体状况',`${choice('body.status',['无异常','局部不适'],false,v.body?.status)}${v.body?.status==='局部不适'?text('body.symptom','具体症状',v.body?.symptom):''}<div class="field"><label class="label">经期</label>${choice('body.period',['否','是'],false,v.body?.period||'否')}</div>${v.body?.period==='是'?`<div class="field"><label class="label">今天是月经第几天</label>${choice('body.periodDay',['1','2','3','4','5','6','7'],false,v.body?.periodDay)}</div><div class="field"><label class="label">经期症状（可多选）</label>${choice('body.periodSymptoms',opts.periodSymptoms,true,v.body?.periodSymptoms||[])}</div>`:''}`,'#bf7790');
content+=section('fart','放屁情况',entries('farts','添加一次放屁',(x)=>`${input('time','放屁时间','time',x.time)}<div class="field"><label class="label">放屁类型</label>${choice('type',opts.fart,false,x.type)}</div>`),'#8c9e78');
content+=section('emotion','情绪',entries('emotions','添加一个时段',(x)=>`<div class="field"><label class="label">时段</label>${choice('period',['上午','中午','下午','晚上'],false,x.period)}</div><div class="field"><label class="label">情绪</label>${choice('mood',opts.emotion,false,x.mood)}</div>${text('note','备注 / 具体事件',x.note)}`),'#bf7790');
content+=section('work','工作',`${choice('work.done',['是','否'],false,v.work?.done)}${v.work?.done==='是'?text('work.note','电商事情相关进展',v.work?.note):''}`,'#49655b');
content+=section('social','人际',entries('socials','添加一次交际',(x)=>`${text('who','和谁交际了',x.who)}<div class="field"><label class="label">交际方式</label>${choice('method',opts.social,false,x.method)}</div>${text('feeling','交际后的感受',x.feeling)}`),'#aa8aaf');
content+=section('medicine','药物与补剂',`${choice('medicine.took',['否','是'],false,v.medicine?.took||'否')}${v.medicine?.took==='是'?entries('doses','添加一次服用',(x)=>`${input('time','服用时间','time',x.time)}<div class="field"><label class="label">补剂类型</label>${choice('supplement',opts.supplements,false,x.supplement)}</div>${input('drug','药名（如有用药）','text',x.drug)}<div class="field"><label class="label">服用片数</label>${choice('count',['1','2','3','4','5'],false,x.count)}</div>`):''}`,'#5e8d82');
content+=section('reading','看书',`${choice('reading.done',['是','否'],false,v.reading?.done)}${v.reading?.done==='是'?text('reading.note','读了什么，有什么收获',v.reading?.note):''}`,'#7799ad');
content+=section('event','重要事件',text('event.note','今天发生了什么，有什么感受',v.event?.note),'#db8c70');return head+content}
function scores(v){if(!v)return [0,0,0,0];let sleep=v.sleep?.start&&v.sleep?.end&&v.sleep?.quality==='好'?1:0;let ex=v.exercise?.type?1:0;let st=(v.stools||[]).filter(x=>x.time).length;let move=ex&&st>=1&&st<=2?1:0;let map={开心:100,激动:40,平静:100,一般:50,沮丧:20,愤怒:20,伤感:20,焦虑:20};let es=v.emotions||[], mood=es.length===4&&es.every(x=>x.mood)?es.reduce((a,x)=>a+map[x.mood],0)/400:0;let learn=(v.work?.done==='是'?0.5:0)+(v.reading?.done==='是'?0.5:0);return [sleep,move,mood,learn]}
function calendar(){let y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate();let cells=Array(first).fill('<div class="day empty"></div>');for(let n=1;n<=days;n++){let ds=`${y}-${String(m+1).padStart(2,'0')}-${String(n).padStart(2,'0')}`,s=scores(db[ds]),colors=['#7799ad','#db8c70','#bf7790','#49655b'];cells.push(`<button class="day ${ds===today()?'today':''}" data-date="${ds}"><div class="day-num">${n}</div><div class="rings">${s.map((q,i)=>`<i class="ring ${q>=.5?'on':''}" style="--c:${colors[i]}"></i>`).join('')}</div></button>`)}return `<div class="calendar-header"><button class="back" data-view="today">‹</button><h1>${y} 年 ${m+1} 月</h1><div class="nav"><button data-month="-1">‹</button><button data-month="1">›</button></div></div><div class="weekdays"><span>日</span><span>一</span><span>二</span><span>三</span><span>四</span><span>五</span><span>六</span></div><div class="grid">${cells.join('')}</div><div class="legend"><span><i style="--c:#7799ad"></i>睡眠</span><span><i style="--c:#db8c70"></i>运动＋排便</span><span><i style="--c:#bf7790"></i>心情</span><span><i style="--c:#49655b"></i>工作＋看书</span></div><p class="notice">圆点会随记录完成度填满。睡眠暂以“超过 8 小时且质量好”为满分。</p>`}
function settings(){return `<header class="top"><div><div class="date">设置</div><div class="subdate">数据只保存在这台 iPhone</div></div><button class="back" data-view="today">‹</button></header><div class="settings"><h2>备份</h2><button class="action" data-export="all">导出全部日志</button><p class="notice">将下载一个 JSON 文件。请保存到“文件”中，换手机或清理浏览器前可用它留存备份。</p><h2>使用提示</h2><p class="notice">在 Safari 中打开后，点击“分享”→“添加到主屏幕”，即可像 App 一样使用。所有填写内容会自动保存。</p></div>`}
function render(){document.getElementById('app').innerHTML=view==='today'?todayPage():view==='calendar'?calendar():settings();bind()}
function pathSet(obj,path,value){let parts=path.split('.'),last=parts.pop();let cur=obj;parts.forEach(p=>cur=cur[p]||(cur[p]={}));cur[last]=value}
function currentEntry(el){let p=el.closest('[data-entry]');if(!p)return log();let a=log()[p.dataset.entry]||(log()[p.dataset.entry]=[]);return a[+p.dataset.index]||(a[+p.dataset.index]={})}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{open=open===b.dataset.toggle?null:b.dataset.toggle;render()});document.querySelectorAll('[data-month]').forEach(b=>b.onclick=()=>{month.setMonth(month.getMonth()+ +b.dataset.month);render()});document.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{selected=b.dataset.date;view='today';open=null;render()});document.querySelectorAll('[data-field]').forEach(el=>el.onchange=()=>{pathSet(currentEntry(el),el.dataset.field,el.value);save();render()});document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{let obj=currentEntry(b),k=b.dataset.choice,old=k.split('.').reduce((a,x)=>a?.[x],obj);let val=b.dataset.value;if(b.dataset.multi==='true'){let a=old||[];pathSet(obj,k,a.includes(val)?a.filter(x=>x!==val):[...a,val])}else pathSet(obj,k,val);save();render()});document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{let a=log()[b.dataset.add]||(log()[b.dataset.add]=[]);a.push({});save();render()});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{log()[b.dataset.remove].splice(+b.dataset.index,1);save();render()});let ex=document.querySelector('[data-export]');if(ex)ex.onclick=exportData}
function exportData(){let blob=new Blob([JSON.stringify({app:'大屁日志',exportedAt:new Date().toISOString(),logs:db},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`大屁日志备份-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();
